name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: psf/black@25.9.0

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: tsuyoshicho/action-mypy@v5.1.1

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dciborow/action-pylint@0.1.1

  stestr:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
      - run: uv sync
      - run: uv run stestr run --slowest --parallel --subunit | uv run subunit2junitxml -o junit.xml
      - uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: junit.xml
